futures: true
symbols:
  - "BINANCE:ENAUSDT"
  - "BINANCE:ETHUSDT"
  - "BINANCE:BTCUSDT"
  - "BINANCE:SOLUSDT"
  - "BINANCE:XPLUSDT"
  - "BINANCE:ASTERUSDT"
  - "BINANCE:DOGEUSDT"
  - "BINANCE:XRPUSDT"
  - "BINANCE:SUIUSDT"
timeframes:
  - "1m"
  - "3m"
  - "5m"
htf_timeframes:
  - "15m"
  - "1h"
periods:
  - {from: "2024-01-01", to: "2025-09-25"}
fees:
  commission_pct: 0.0005
  slippage_ticks: 2
risk:
  leverage: 10
  qty_pct: 30
  liq_buffer_pct: 0.5
symbol_aliases:
  "BINANCE:XPLUSDT": "BINANCE:XPLAUSDT"
  "BINANCE:ASTERUSDT": "BINANCE:ASTRUSDT"
